#ifndef OWL_SHADER_LIBRARY_VERSION_LIB
#define OWL_SHADER_LIBRARY_VERSION_LIB

#ifndef SHADER_LIB_VERSION
	#if UNITY_VERSION > 202100
	#define SHADER_LIB_VERSION 2021
	#elif UNITY_VERSION > 202000
	#define SHADER_LIB_VERSION 2020
	#elif UNITY_VERSION > 201900
	#define SHADER_LIB_VERSION 2019
	#endif
#endif
#endif